### ISSUE TITLE
mia::importHUMAnN() problem

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#627] opened 2024-08-13 12:36 UTC
Critical sample matching issue reported in:
https://github.com/finrisk2002/finriskR/issues/34

Related to #622

**Comment by antagomir** [comment] 2024-11-03 19:47
Was this already solved? @himmil do you know?

**Comment by himmil** [comment] 2024-11-05 07:41
I don't actually know. This is not related to the missing hyphen issue

**Comment by TuomasBorman** [comment] 2024-11-06 17:28
What I understood from the issue in Finrisk was that the issue is not in mia but in Finrisk code. This issue can be closed in mia; the issue in Finrisk stays open.

**Closed as completed by TuomasBorman** 2024-11-06 17:28 UTC
