### ISSUE TITLE
getCrossAssociation, critical bug?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#649] opened 2024-10-16 07:57 UTC
**Describe the bug**

`getCrossAssociation` seems to generate feature x feature association table with a call that I expected to generate association table between colData variables.

**To Reproduce**
A clear and concise description of how to reproduce the behavior.

```
data(GlobalPatterns, package="mia")
tse <- GlobalPatterns
rownames(tse) <- paste0("ASV", 1:nrow(tse))
M <- matrix(sample(4*ncol(tse)), ncol=4); colnames(M) <- c("A", "B", "C", "D")
colData(tse) <- cbind(colData(tse), M)
xxx <- getCrossAssociation(tse[1:100,],
                                     # Top ARG classes, count assay
                                     colData_variable1 = c("A", "B"),
				     # ... correlated with colData columns starting with "nmf"
                                     colData_variable2 = c("C", "D"),
				     # use Kendall's tau for robustness
                                     method = "kendall",
				     mode = "table",
				     p.adj.method="fdr",
				     test.signif = TRUE)
```

**Expected behavior**

I expected to generate association table between colData variables (AB vs CD)

**Comment by TuomasBorman** [comment] 2024-10-16 08:16
The problem is that for `SummarizedExperiment` the old parameter names are not supported.

This works

```
res <- getCrossAssociation(
    tse[1:100,],
    # Top ARG classes, count assay
    colData_variable1 = c("A", "B"),
    # ... correlated with colData columns starting with "nmf"
    colData_variable2 = c("C", "D"),
    # use Kendall's tau for robustness
    method = "kendall",
    mode = "table",
    p.adj.method="fdr",
    test.signif = TRUE)
res
```

This will fix the problem:

lines 368 and 369 from [here](https://github.com/microbiome/mia/blob/c76bc909b1dc8f30886ada7cdbc94138c592a14c/R/getCrossAssociation.R#L368)

```
col.var1 = NULL,
col.var2 = NULL,
```
should be changed to
```
col.var1 = colData_variable1, colData_variable1= NULL,
col.var2 = colData_variable2, colData_variable2 =  NULL,
```

However, the problem is that this error will be in next release. The release can be modified but it is not recommended. The documentation states that one should use these new parameters.

**Comment by antagomir** [comment] 2024-10-16 10:59
This can easily lead to mistakes. I think that this is an example about a situation where modifying the release version would be justified and probably a good idea.

**Comment by antagomir** [comment] 2024-10-16 11:00
If using the release leads to gross errors it should be fixed in my view.

**Comment by TuomasBorman** [comment] 2024-10-16 11:10
I agree (although, this should be something that user should easily see based on results and documentation), however, we should wait until the release is published.

**Closed as completed** 2024-10-21 21:13 UTC
